using Lft.Domain.Models;

namespace Lft.Engine;

public sealed class DummyCodeGenerationEngine : ICodeGenerationEngine
{
    public Task<GenerationResult> GenerateAsync(GenerationRequest request, CancellationToken cancellationToken = default)
    {
        var filePath = $"Dummy/{request.EntityName}.txt";

        var content = $"""
            // Dummy code generated by LFT
            // Entity: {request.EntityName}
            // Language: {request.Language}

            // TODO: Replace this with real template-based generation in Sprint 2.
            """;

        var files = new[]
        {
            new GeneratedFile(filePath, content)
        };

        var result = new GenerationResult(files);
        return Task.FromResult(result);
    }
}
